# Generated by Django 5.2.8 on 2025-11-17 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('design', 'Design'), ('marketing', 'Marketing'), ('coding', 'Coding'), ('data_analysis', 'Data Analysis'), ('psychology', 'Psychology'), ('research', 'Research'), ('content_writing', 'Content Writing'), ('business_strategy', 'Business Strategy'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('team_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=20)),
                ('team_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('eligible_departments', models.TextField(blank=True, help_text='Comma-separated departments, leave blank for all')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('eligible_years', models.CharField(blank=True, help_text='e.g., 2,3,4', max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('milestone', 'Milestone-based')], default='fixed', max_length=20)),
                ('duration_weeks', models.IntegerField(help_text='Expected project duration in weeks')),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending University Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('open', 'Open for Applications'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_projects', to='accounts.student')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.university')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('payment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('revision_required', 'Revision Required')], default='pending', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='deliverables/')),
                ('submission_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('revision_required', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='accounts.student')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='projects.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
            ],
            options={
                'db_table': 'deliverables',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('proposed_approach', models.TextField(blank=True)),
                ('portfolio_links', models.TextField(blank=True)),
                ('is_team_application', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.student')),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_applications', to='accounts.student')),
            ],
            options={
                'db_table': 'project_applications',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'student')},
            },
        ),
    ]
