# Generated by Django 5.2.8 on 2025-12-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='posted_by_university',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='poster_type',
            field=models.CharField(choices=[('company', 'Company'), ('university', 'University')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending University Review'), ('rejected', 'Rejected'), ('open', 'Open for Applications'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
