# Generated by Django 5.2.8 on 2025-12-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_posted_by_university_project_poster_type_and_more'),
        ('projects', '0003_add_job_type'),
    ]

    operations = [
    ]
