# Generated by Django 5.2.8 on 2026-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_merge_20251205_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload the detailed job description document', null=True, upload_to='project_attachments/', verbose_name='Job Description (JD)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(verbose_name='Project Closure Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remuneration Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('milestone', 'Milestone-based')], default='fixed', max_length=20, verbose_name='Remuneration Type'),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
