# Generated by Django 5.2.8 on 2026-01-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_skills_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='Company Registration/CIN Number', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Number (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(help_text='Official company email', max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(help_text='SPOC (Single Point of Contact)', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Upload company registration certificate, GST certificate, or incorporation documents', null=True, upload_to='company_docs/'),
        ),
    ]
